name: Send Email

on:
  schedule:
    - cron: '10 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run send_email.py script
        run: |
          python send_email.py
        env:
          JENKINS_PASSWORD: ${{ secrets.JENKINS_PASSWORD }}
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
